server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keep
    username: keep
    password: keep
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

config:
  api:
    jwt:
      secret: configApiSecret
      expiration: 8640000